[package]
name = "meta_parsegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
meta_parsegen_derive = { path = './meta_parsegen_derive' }
